k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: true
    showTime: false
  currentContext: delfingen-dev
  currentCluster: gke_ebusiness-ita864ff708_europe-west1_delfingen-dev
  clusters:
    gke_catalogue-bench_europe-west1_catalogue-bench:
      namespace:
        active: all
        favorites:
        - all
        - bench
        - default
      view:
        active: servicemonitor
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_ebusiness-ita864ff708_europe-west1_delfingen-dev:
      namespace:
        active: default
        favorites:
        - default
        - integration
        - validation
        - crossplane-system
        - external-secrets
        - all
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_neo9-catalogue-259610_europe-west1_catalogue-dev:
      namespace:
        active: validation
        favorites:
        - monitoring
        - system-tools
        - efk
        - validation
        - integration
        - kube-system
        - all
        - default
      view:
        active: jobs
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_neo9-software-factory_europe-west1_sf:
      namespace:
        active: gitlab
        favorites:
        - sonarqube
        - keycloak
        - gitlab
        - crossplane-system
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    kind-kind:
      namespace:
        active: default
        favorites:
        - all
        - default
      view:
        active: secrets
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    neokube:
      namespace:
        active: all
        favorites:
        - patch-operator
        - all
        - default
      view:
        active: issuers
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-cmizzi
