add_newline  = true
prompt_order = [
	"username",
	"directory",
	"git_branch",
	"git_commit",
	"git_status",
	"cmd_duration",
	"jobs",
	"line_break",
	"character",
]

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"

[cmd_duration]
min_time = 0
prefix = ""

[git_branch]
prefix = ""

[git_commit]
disabled = false
