#! /bin/sh

xrandr --output DP-0 --mode 2560x1440 --rate 180 --auto --primary --output DP-2 --mode 2560x1440 --rate 180 --auto --right-of DP-0
# xrandr --output DP-2 --off --output DP-0 --mode 2560x1440 --rate 180 --auto --primary --output HDMI-0 --mode 1920x1080 --rate 60 --auto --right-of DP-0

# Startup scripts {{{
setxkbmap -layout us,fr -option ''
sxhkd &
numlockx on &
autocutsel -selection PRIMARY -fork &
compton &
xautolock -time 30 -locker 'i3lock-fancy' -corners 0000 &
xsetroot -cursor_name left_ptr &
copyq &
sleep 1

feh --randomize --bg-fill ~/Pictures/Wallpapers
conky &
stalonetray &
blueman-applet &
polybar --config=~/.config/polybar/config.ini main &
# }}}

# Monitor configuration {{{

bspc monitor DP-0 -n left -d I II III IV V
bspc monitor DP-2 -n right -d VI VII VIII IX X
# bspc monitor HDMI-0 -n right -d VI VII VIII IX X

# Global configuration {{{
bspc config initial_polarity      second_child
bspc config border_width          0
bspc config border_radius         8
bspc config window_gap            18
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config focused_border_color '#e1b2d4'
bspc config normal_border_color '#1A1826'
bspc config -m right top_padding 0
bspc config -m right left_padding 0
bspc config -m right right_padding 0
bspc config -m right bottom_padding 0
bspc config -m left top_padding 51
bspc config -m left left_padding 0
bspc config -m left right_padding 0
bspc config -m left bottom_padding 0
# }}}

# Internal rules {{{
bspc rule -a google-chrome-stable desktop='^I'
bspc rule -a thunderbird desktop='^VIII'
bspc rule -a discord desktop='^IX'
bspc rule -a git-cola state=floating
bspc rule -a zazu state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a copyq state=floating follow=on
bspc rule -a dunst state=floating
bspc rule -a dunst state=floating
bspc rule -a UnrealEditor state=floating
# }}}

# vim: syn=sh
