#! /bin/sh

# Startup scripts {{{
sxhkd &
numlockx on &
autocutsel -selection PRIMARY -fork &
greenclip daemon &
setxkbmap -layout us,fr -option '' -option grp:alt_space_toggle,grp_led:scroll
xcompmgr &
xautolock -time 10 -locker 'lock' &
clipit &
sleep 1

feh --randomize --bg-fill ~/Pictures/Wallpapers/*
conky &
stalonetray &
# }}}

# Monitor configuration {{{
bspc monitor DP-1 -n left -d I II III IV
bspc monitor HDMI-2 -n right -d V VI VII VIII IX X
# }}}

# Global configuration {{{
bspc config initial_polarity      second_child
bspc config border_width          0
bspc config window_gap            2
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config focused_border_color  "#1d1f21"
bspc config normal_border_color   "#a8b0b8"
bspc config presel_feedback_color "#f0bb48"
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config -m left left_padding 2
# }}}

# Internal rules {{{
bspc rule -a google-chrome-stable desktop='^I'
bspc rule -a thunderbird desktop='^VIII'
bspc rule -a discord desktop='^IX'
bspc rule -a git-cola state=floating
bspc rule -a zazu state=floating
# }}}

# vim: syn=sh
