#! /bin/sh

xrandr --output DP-0 --mode 1920x1080 --rate 165.00 --primary --output DP-2 --mode 1920x1080 --rate 165.00 --right-of DP-0

# Startup scripts {{{
setxkbmap -layout us,fr -option ''
sxhkd &
numlockx on &
autocutsel -selection PRIMARY -fork &
greenclip daemon &
compton &
xautolock -time 30 -locker 'i3lock' -corners 0000 &
xsetroot -cursor_name left_ptr &
copyq &
/home/cyril/.local/bin/synconfig
sleep 1

feh --randomize --bg-max ~/Pictures/Wallpapers
conky &
stalonetray &
polybar --config=~/.config/polybar/config.ini main &
dropbox start &
# }}}

# Monitor configuration {{{

# Tree screens, disabled lid.
bspc monitor DP-0 -n left -d I II III IV V
bspc monitor DP-2 -n right -d VI VII VIII IX X

# Global configuration {{{
bspc config initial_polarity      second_child
bspc config border_width          0
bspc config border_radius         8
bspc config window_gap            18
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config focused_border_color '#e1b2d4'
bspc config normal_border_color '#1A1826'
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config -m left top_padding 51
# }}}

# Internal rules {{{
bspc rule -a google-chrome-stable desktop='^I'
bspc rule -a thunderbird desktop='^VIII'
bspc rule -a discord desktop='^IX'
bspc rule -a git-cola state=floating
bspc rule -a zazu state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a copyq state=floating
bspc rule -a dunst state=floating
# }}}

# vim: syn=sh
