;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   Created By Aditya Shakya.
;
;==========================================================

include-file = ~/.config/polybar/colors.ini

[bar/main]
width = 98.1%
# width = 85.1%
height = 40
offset-x = 1%
radius = 1
offset-y = 8
fixed-center = true
background = ${color.background}
foreground = ${color.foreground}
override-redirect = true

line-size = 3
line-color = ${color.background}

border-size = 5
border-color = ${color.background}

padding-left = 0
padding-right = 0

module-margin-left = 0
module-margin-right = 0

font-0 = "FiraMono for Powerline:pixelsize=16;4"
font-1 = "MonoLisa Nerd Font Mono:pixelsize=14;4"
font-2 = "MonoLisa Nerd Font Mono:pixelsize=28;4"
font-3 = "Material Icons:22;4"
font-4 = "terminus:pixelsize=12"
font-5 = "Weather Icons:size=12;0"
modules-left = ws
modules-center =
modules-right = lyrics gap weather gap pulseaudio gap date time gap

wm-restack = bspwm
cursor-click = pointer
cursor-scroll = ns-resize

[module/weather]
type = custom/script
exec = ~/.config/polybar/polybar-forecast-linux-x86_64
exec-if = ping openweathermap.org -c 1
interval = 600
format-font = 6
format-padding = 1

[module/ws]
type = internal/bspwm
pin-workspaces = false
enable-click = true
enable-scroll = false
label-focused = %icon%
label-focused-padding = 1
label-focused-margin = 10px
label-occupied = %icon%
label-occupied-padding = 1
label-occupied-margin = 10px
label-urgent = %icon%
label-urgent-padding = 1
label-urgent-margin = 10px
label-empty = %icon%
label-empty-padding = 1
label-empty-margin = 10px
format-font = 3
label-occupied-underline = ${color.foreground}
label-occupied-foreground = ${color.foreground}
label-focused-underline = ${color.yellow}
label-focused-foreground = ${color.yellow}
inline-mode = false
format = <label-state> <label-mode>
ws-icon-0 = I;
ws-icon-1 = II;
ws-icon-2 = VII;
ws-icon-3 = VIII;
ws-icon-4 = IX;
ws-icon-5 = X;
ws-icon-default = 
# type = internal/xworkspaces
# enable-scroll = false
# label-active = %icon%
# label-active-foreground = ${color.yellow}
# #label-active-background = ${color.background}
# label-active-underline = ${color.yellow}
# label-occupied = %icon%
# label-occupied-underline = ${color.overlay}
# label-occupied-foreground = ${color.foreground}
# label-empty = %icon%
# label-empty-foreground = ${color.foreground}
# format-font = 3
# label-active-padding = 1
# label-occupied-padding = 1
# label-empty-padding = 1

[module/date]
type = internal/date
interval = 1
format-foreground = ${color.foreground}
date = "%a %d/%m"
format-prefix = "%{T3} %{T1}"
format-prefix-foreground = ${color.foreground}
format-padding = 1
label = "%date%"

[module/time]
type = internal/date
interval = 1
timea-alt = "%I:%M %p"
time = %H:%M
format-foreground = ${color.foreground}
# format-background = ${color.background}
label = %time%

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
format-prefix = ""
label-volume = "%{T3} %{T1}%percentage%%"
label-volume-foreground = ${color.foreground}
label-volume-spacing = 0
label-volume-padding = 0
format-padding = 1

label-muted =  "%{T3}"
# label-muted-background = ${color.background}
label-muted-foreground = ${color.foreground}

[module/gap]
type = custom/text
format = " "
format-padding = 10px

[module/lyrics]
type = custom/script
exec = mpris-lyrics-cli --pipe
tail = true
interval = 0
format-padding = 4
format-prefix = "🎙"
format-prefix-foreground = ${color.foreground}
content-foreground = ${color.foreground}
content-background = ${color.background}

[settings]
screenchange-reload = true

[global/wm]
margin-top = 0
margin-bottom = 5

; vim:ft=dosini
